import { createContext, useContext, useState, type ReactNode } from 'react';

export type Lang = 'VN' | 'EN';

type T = Record<string, string>;

const vn: T = {
  // Nav
  'nav.home': 'Trang Chủ',
  'nav.services': 'Dịch Vụ',
  'nav.projects': 'Dự Án',
  'nav.about': 'Về Chúng Tôi',
  'nav.journal': 'Tạp Chí',
  'nav.contact': 'Liên Hệ',
  // Footer
  'footer.tagline': 'Sự xuất sắc trong kiến trúc thông qua triết lý tối giản và tay nghề thủ công bậc thầy.',
  'footer.office': 'Văn Phòng',
  'footer.address': 'Tầng 42, Bitexco Financial Tower',
  'footer.city': 'TP. Hồ Chí Minh, Việt Nam',
  'footer.phone': '+84 (0) 909 123 456',
  'footer.legal': 'Pháp Lý & Bền Vững',
  'footer.privacy': 'Chính Sách Bảo Mật',
  'footer.terms': 'Điều Khoản Dịch Vụ',
  'footer.sustainability': 'Phát Triển Bền Vững',
  'footer.press': 'Báo Chí',
  'footer.copyright': '© 2024 VIETDESIGN. KIẾN TRÚC & NỘI THẤT.',
  // Home
  'home.hero.subtitle': 'Sự Trường Tồn Của Kiến Trúc',
  'home.hero.title1': 'BỘ SƯU TẬP',
  'home.hero.cta': 'Xem Dự Án',
  'home.stats.years': 'Năm Kinh Nghiệm',
  'home.stats.projects': 'Dự Án Hoàn Thành',
  'home.stats.satisfaction': 'Khách Hàng Hài Lòng',
  'home.stats.awards': 'Giải Thưởng',
  'home.practice.title': 'Thực Hành',
  'home.practice.desc': 'Chúng tôi mang đến sự chuyển đổi mượt mà từ bản phác thảo ý tưởng đến hiện thực hóa không gian vật lý.',
  'home.practice.tagline': 'Kiến Tạo Tương Lai',
  'home.card1.title': 'Thiết Kế Kiến Trúc',
  'home.card1.desc': 'Điêu khắc các khoảng trống và khối đặc để tạo ra những môi trường sống gợi cảm xúc vượt qua các xu hướng tạm thời.',
  'home.card2.title': 'Thiết Kế & Thi Công',
  'home.card2.desc': 'Một cách tiếp cận toàn diện đảm bảo ý đồ kiến trúc được giữ gìn từ viên đá đầu tiên đến lớp hoàn thiện cuối cùng.',
  'home.explore': 'Khám Phá Dịch Vụ',
  'home.featured.title': 'Kiệt Tác Tuyển Chọn',
  'home.proj1.cat': 'Dân Dụng / Sài Gòn',
  'home.proj2.cat': 'Nội Thất / Đà Lạt',
  'home.proj3.cat': 'Thương Mại / Hà Nội',
  'home.proj4.cat': 'Bespoke / Phú Quốc',
  'home.proj5.cat': 'Nghệ Thuật / Singapore',
  'home.proj6.cat': 'Văn Phòng / Tokyo',
  'home.why.title1': 'Sự Thuần Khiết Kiến Trúc',
  'home.why.desc1': 'Tôn vinh vật liệu và hình khối mà không bị nhiễu bởi những chi tiết trang trí thừa thãi.',
  'home.why.title2': 'Vật Liệu Tinh Tế',
  'home.why.desc2': 'Tuyển chọn đá quý hiếm, gỗ tái sinh và kim loại thủ công từ khắp nơi trên thế giới.',
  'home.why.title3': 'Chất Lượng Tuyệt Đối',
  'home.why.desc3': 'Kỹ thuật chính xác kết hợp với tay nghề thủ công trong từng mối nối và bề mặt.',
  'home.why.title4': 'Di Sản Bền Vững',
  'home.why.desc4': 'Thiết kế cho thế kỷ tiếp theo, ưu tiên sự hài hòa với môi trường và độ bền bỉ.',
  'home.testimonial': '"VIETDESIGN đã biến tầm nhìn của chúng tôi thành một kiệt tác vật lý. Sự chú ý của họ đến sự giao thoa giữa bóng tối và ánh sáng là vô song trong kiến trúc hiện đại."',
  'home.testimonial.author': 'Alexander Võ, CEO của Aurora Group',
  'home.cta.title': 'Bắt Đầu Dự Án Di Sản Của Bạn',
  'home.cta.btn': 'Liên Hệ Ngay',
  // About
  'about.label': 'Câu Chuyện Của Chúng Tôi',
  'about.title': 'KIẾN TẠO DI SẢN',
  'about.desc': 'Thành lập năm 2009, VIETDESIGN bắt đầu với một triết lý đơn giản: kiến trúc phải là sự phản chiếu chân thực của thời đại, đồng thời mang trong mình giá trị vượt thời gian. Chúng tôi không chạy theo xu hướng, chúng tôi tìm kiếm sự vĩnh cửu trong từng đường nét.',
  'about.philosophy.title': 'Triết Lý Thiết Kế',
  'about.philosophy.quote': '"Chúng tôi tin rằng không gian sống có sức mạnh định hình cảm xúc và hành vi con người. Một thiết kế xuất sắc không chỉ giải quyết bài toán công năng mà còn phải chạm đến tâm hồn, tạo ra một nơi chốn mà con người thực sự thuộc về."',
  'about.team.title': 'Đội Ngũ Lãnh Đạo',
  'about.team.m1.name': 'Lê Hoàng',
  'about.team.m1.role': 'Nhà Sáng Lập / Kiến Trúc Sư Trưởng',
  'about.team.m2.name': 'Trần Mai',
  'about.team.m2.role': 'Giám Đốc Thiết Kế Nội Thất',
  'about.team.m3.name': 'Phạm Tuấn',
  'about.team.m3.role': 'Giám Đốc Quản Lý Dự Án',
  // Services
  'services.label': 'Chuyên Môn',
  'services.title': 'DỊCH VỤ CỦA CHÚNG TÔI',
  'services.s1.title': 'Thiết Kế Kiến Trúc',
  'services.s1.desc': 'Chúng tôi tiếp cận kiến trúc như một hình thức điêu khắc không gian sống. Mỗi dự án bắt đầu bằng việc nghiên cứu kỹ lưỡng về địa hình, ánh sáng tự nhiên và bối cảnh văn hóa. Kết quả là những công trình không chỉ đẹp mắt mà còn hòa quyện hoàn hảo với môi trường xung quanh, tạo ra những trải nghiệm không gian độc đáo và bền vững.',
  'services.s1.li1': 'Nghiên cứu & Quy hoạch tổng thể',
  'services.s1.li2': 'Thiết kế ý tưởng & Phát triển',
  'services.s1.li3': 'Hồ sơ kỹ thuật thi công',
  'services.s1.li4': 'Giám sát tác giả',
  'services.s2.title': 'Thiết Kế Nội Thất',
  'services.s2.desc': 'Nội thất là linh hồn của kiến trúc. Chúng tôi tạo ra những không gian bên trong phản ánh cá tính và phong cách sống của chủ nhân. Từ việc lựa chọn vật liệu cao cấp, ánh sáng tinh tế đến những món đồ nội thất được thiết kế riêng (bespoke), mọi chi tiết đều được chăm chút để mang lại sự sang trọng, thoải mái và công năng tối ưu.',
  'services.s2.li1': 'Thiết kế không gian & Phân bổ công năng',
  'services.s2.li2': 'Lựa chọn vật liệu & Hoàn thiện',
  'services.s2.li3': 'Thiết kế ánh sáng nghệ thuật',
  'services.s2.li4': 'Thiết kế đồ nội thất Bespoke',
  'services.s3.title': 'Thi Công & Quản Lý Dự Án',
  'services.s3.desc': 'Để đảm bảo ý tưởng thiết kế được hiện thực hóa một cách hoàn hảo nhất, chúng tôi cung cấp dịch vụ thi công và quản lý dự án trọn gói. Đội ngũ kỹ sư và thợ thủ công lành nghề của chúng tôi làm việc với sự tỉ mỉ và tiêu chuẩn khắt khe nhất, đảm bảo tiến độ, chất lượng và sự an tâm tuyệt đối cho khách hàng.',
  'services.s3.li1': 'Quản lý ngân sách & Tiến độ',
  'services.s3.li2': 'Thi công xây dựng & Hoàn thiện',
  'services.s3.li3': 'Sản xuất & Lắp đặt nội thất',
  'services.s3.li4': 'Bàn giao & Bảo hành',
  // Projects
  'projects.label': 'Danh Mục Đầu Tư',
  'projects.title': 'DỰ ÁN TIÊU BIỂU',
  'projects.filter.all': 'Tất Cả',
  'projects.filter.villa': 'Villa',
  'projects.filter.canho': 'Căn Hộ',
  'projects.filter.kientruc': 'Kiến Trúc',
  'projects.loadmore': 'Tải Thêm Dự Án',
  'projects.placeholder': '[ADMIN CÓ THỂ THAY ẢNH NÀY]',
  // Contact
  'contact.label': 'Kết Nối',
  'contact.title': 'LIÊN HỆ',
  'contact.office.title': 'Văn Phòng Chính',
  'contact.office.addr1': 'Tầng 42, Bitexco Financial Tower',
  'contact.office.addr2': '2 Hải Triều, Quận 1',
  'contact.office.addr3': 'TP. Hồ Chí Minh, Việt Nam',
  'contact.info.title': 'Thông Tin Liên Lạc',
  'contact.info.phone': 'T: +84 (0) 909 123 456',
  'contact.info.email': 'E: hello@vietdesign.com',
  'contact.hours.title': 'Giờ Làm Việc',
  'contact.hours.weekday': 'Thứ Hai - Thứ Sáu: 9:00 - 18:00',
  'contact.hours.weekend': 'Thứ Bảy, Chủ Nhật: Đóng cửa',
  'contact.form.title': 'Gửi Yêu Cầu Tư Vấn',
  'contact.form.name': 'Họ và Tên *',
  'contact.form.phone': 'Số Điện Thoại *',
  'contact.form.email': 'Email *',
  'contact.form.service': 'Dịch Vụ Quan Tâm',
  'contact.form.message': 'Nội Dung Chi Tiết',
  'contact.form.submit': 'Gửi Yêu Cầu',
  'contact.form.success': 'Cảm ơn! Chúng tôi sẽ liên hệ với bạn trong thời gian sớm nhất.',
  'contact.err.name': 'Vui lòng nhập họ và tên.',
  'contact.err.phone': 'Vui lòng nhập số điện thoại hợp lệ.',
  'contact.err.email': 'Vui lòng nhập địa chỉ email hợp lệ.',
  'contact.svc.arch': 'Thiết Kế Kiến Trúc',
  'contact.svc.interior': 'Thiết Kế Nội Thất',
  'contact.svc.construction': 'Thi Công & Quản Lý',
  'contact.svc.other': 'Khác',
};

const en: T = {
  // Nav
  'nav.home': 'Home',
  'nav.services': 'Services',
  'nav.projects': 'Projects',
  'nav.about': 'About Us',
  'nav.journal': 'Journal',
  'nav.contact': 'Contact',
  // Footer
  'footer.tagline': 'Architectural excellence through minimalist philosophy and masterful craftsmanship.',
  'footer.office': 'Office',
  'footer.address': 'Floor 42, Bitexco Financial Tower',
  'footer.city': 'Ho Chi Minh City, Vietnam',
  'footer.phone': '+84 (0) 909 123 456',
  'footer.legal': 'Legal & Sustainability',
  'footer.privacy': 'Privacy Policy',
  'footer.terms': 'Terms of Service',
  'footer.sustainability': 'Sustainability',
  'footer.press': 'Press',
  'footer.copyright': '© 2024 VIETDESIGN. ARCHITECTURE & INTERIORS.',
  // Home
  'home.hero.subtitle': 'The Permanence of Architecture',
  'home.hero.title1': 'THE COLLECTION',
  'home.hero.cta': 'View Projects',
  'home.stats.years': 'Years of Experience',
  'home.stats.projects': 'Projects Completed',
  'home.stats.satisfaction': 'Client Satisfaction',
  'home.stats.awards': 'Awards Won',
  'home.practice.title': 'Practice',
  'home.practice.desc': 'We deliver a seamless transformation from conceptual sketch to physical spatial realization.',
  'home.practice.tagline': 'Building The Future',
  'home.card1.title': 'Architectural Design',
  'home.card1.desc': 'Sculpting voids and solids to create emotionally resonant living environments that transcend temporary trends.',
  'home.card2.title': 'Design & Build',
  'home.card2.desc': 'A comprehensive approach ensuring architectural intent is preserved from the first stone to the final finish.',
  'home.explore': 'Explore Services',
  'home.featured.title': 'Selected Masterworks',
  'home.proj1.cat': 'Residential / Saigon',
  'home.proj2.cat': 'Interiors / Da Lat',
  'home.proj3.cat': 'Commercial / Hanoi',
  'home.proj4.cat': 'Bespoke / Phu Quoc',
  'home.proj5.cat': 'Arts / Singapore',
  'home.proj6.cat': 'Office / Tokyo',
  'home.why.title1': 'Architectural Purity',
  'home.why.desc1': 'Celebrating materials and forms without the noise of superfluous decorative details.',
  'home.why.title2': 'Refined Materials',
  'home.why.desc2': 'Sourcing rare stone, reclaimed timber and custom metalwork from across the globe.',
  'home.why.title3': 'Absolute Quality',
  'home.why.desc3': 'Precision engineering combined with artisanal craftsmanship in every joint and surface.',
  'home.why.title4': 'Sustainable Legacy',
  'home.why.desc4': 'Designing for the next century, prioritizing harmony with the environment and longevity.',
  'home.testimonial': '"VIETDESIGN transformed our vision into a physical masterpiece. Their attention to the interplay of shadow and light is unparalleled in modern architecture."',
  'home.testimonial.author': 'Alexander Võ, CEO of Aurora Group',
  'home.cta.title': 'Begin Your Legacy Project',
  'home.cta.btn': 'Contact Us',
  // About
  'about.label': 'Our Story',
  'about.title': 'BUILDING LEGACY',
  'about.desc': "Founded in 2009, VIETDESIGN began with a simple philosophy: architecture must be an authentic reflection of the era, while carrying timeless value. We don't chase trends; we seek eternity in every line.",
  'about.philosophy.title': 'Design Philosophy',
  'about.philosophy.quote': '"We believe living spaces have the power to shape human emotion and behavior. Exceptional design not only resolves functional challenges but must touch the soul, creating a place where people truly belong."',
  'about.team.title': 'Leadership Team',
  'about.team.m1.name': 'Lê Hoàng',
  'about.team.m1.role': 'Founder / Principal Architect',
  'about.team.m2.name': 'Trần Mai',
  'about.team.m2.role': 'Director of Interior Design',
  'about.team.m3.name': 'Phạm Tuấn',
  'about.team.m3.role': 'Director of Project Management',
  // Services
  'services.label': 'Expertise',
  'services.title': 'OUR SERVICES',
  'services.s1.title': 'Architectural Design',
  'services.s1.desc': 'We approach architecture as a form of spatial sculpture. Each project begins with thorough research into terrain, natural light, and cultural context. The result: structures that are not only beautiful but integrate seamlessly with their surroundings.',
  'services.s1.li1': 'Research & Master Planning',
  'services.s1.li2': 'Concept Design & Development',
  'services.s1.li3': 'Technical Construction Documents',
  "services.s1.li4": "Author's Supervision",
  'services.s2.title': 'Interior Design',
  'services.s2.desc': 'Interiors are the soul of architecture. We create inner spaces that reflect the personality and lifestyle of the owner. Every detail is crafted for luxury, comfort, and optimal function.',
  'services.s2.li1': 'Space Planning & Function Allocation',
  'services.s2.li2': 'Material Selection & Finishing',
  'services.s2.li3': 'Artistic Lighting Design',
  'services.s2.li4': 'Bespoke Furniture Design',
  'services.s3.title': 'Construction & Project Management',
  'services.s3.desc': 'To ensure design ideas are realized as perfectly as possible, we offer a full construction and project management service. Guaranteeing progress, quality, and total peace of mind for our clients.',
  'services.s3.li1': 'Budget & Schedule Management',
  'services.s3.li2': 'Construction & Finishing',
  'services.s3.li3': 'Furniture Manufacturing & Installation',
  'services.s3.li4': 'Handover & Warranty',
  // Projects
  'projects.label': 'Investment Portfolio',
  'projects.title': 'FEATURED PROJECTS',
  'projects.filter.all': 'All',
  'projects.filter.villa': 'Villa',
  'projects.filter.canho': 'Apartment',
  'projects.filter.kientruc': 'Architecture',
  'projects.loadmore': 'Load More Projects',
  'projects.placeholder': '[ADMIN CAN REPLACE THIS IMAGE]',
  // Contact
  'contact.label': 'Connect',
  'contact.title': 'CONTACT',
  'contact.office.title': 'Main Office',
  'contact.office.addr1': 'Floor 42, Bitexco Financial Tower',
  'contact.office.addr2': '2 Hai Trieu, District 1',
  'contact.office.addr3': 'Ho Chi Minh City, Vietnam',
  'contact.info.title': 'Contact Information',
  'contact.info.phone': 'T: +84 (0) 909 123 456',
  'contact.info.email': 'E: hello@vietdesign.com',
  'contact.hours.title': 'Office Hours',
  'contact.hours.weekday': 'Monday – Friday: 9:00 – 18:00',
  'contact.hours.weekend': 'Saturday, Sunday: Closed',
  'contact.form.title': 'Send Consultation Request',
  'contact.form.name': 'Full Name *',
  'contact.form.phone': 'Phone Number *',
  'contact.form.email': 'Email Address *',
  'contact.form.service': 'Service of Interest',
  'contact.form.message': 'Detailed Message',
  'contact.form.submit': 'Send Request',
  'contact.form.success': 'Thank you! We will contact you soon.',
  'contact.err.name': 'Please enter your full name.',
  'contact.err.phone': 'Please enter a valid phone number.',
  'contact.err.email': 'Please enter a valid email address.',
  'contact.svc.arch': 'Architectural Design',
  'contact.svc.interior': 'Interior Design',
  'contact.svc.construction': 'Construction & Management',
  'contact.svc.other': 'Other',
};

interface LangContextType {
  lang: Lang;
  toggleLang: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LangContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('VN');
  const toggleLang = () => setLang(prev => (prev === 'VN' ? 'EN' : 'VN'));
  const t = (key: string): string => (lang === 'VN' ? vn : en)[key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
}
